### ISSUE TITLE
padj value is NA for many genes

### ISSUE THREAD

**Issue by wushaowen1992** [Kan-E/RNAseqChef#1]
Dear developer,
Very good tool. When I used it, I found that whether it is 3 conditions DEG or multi DEG, there will be some genes with obvious fold change, but the padj value can not be calculated (shown as NA), so it was not selected as a differential gene. What's the matter?

**Comment by Kan-E** [comment]
Thank you for reaching out and using RNAseqChef.
 I appreciate your inquiry about the missing padj values for certain genes.
The reasons are as follows.

**For Multi DEG:**
1. All Samples with Zero Counts:
If all samples within a row have zero counts, the baseMean column will be zero. Consequently, log2 fold change estimates, p-value, and adjusted p-value will all be set to NA.
2. Extreme Count Outlier Detection:
If a row contains a sample with an extreme count outlier, p-value, and adjusted p-value will be set to NA. These outlier counts are identified using Cook’s distance.

Multi DEG relies on DESeq2, and you can find detailed information [here](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#pvaluesNA).

**For 3 conditions DEG:**
- The DEG detection function (EBMultiTest()) avoids testing on genes with more than 75% values < 10 to ensure better model fitting.

3 conditions DEG relies on EBSeq, and you can find detailed information [here](https://github.com/lengning/EBSeq#my-favorite-geneisoform-has-na-in-pp-status-notest).

If you have further questions, please don't hesitate to ask.

Best regards,

Kan

**Comment by wushaowen1992** [comment]
Hi Kan, 
Thank you for your detailed information. For multi DEG, I noticed the missing padj genes come from two reasons you mentioned. For 3 conditions, I found not only the reason you mentioned but also rows with high variability.
Nevertheless, I know how to address my issues now.
