### ISSUE TITLE
Troubles with Medicago truncatula list

### ISSUE THREAD

**Issue by Rcabezap** [Kan-E/RNAseqChef#2]
Dear Colleague,

I am contacting you because I am analyzing RNAseq data of Medicago truncatula species in RNAseqChef, however, apparently there is a persistent server error.
biomart has encountered an unexpected server error. Please try using a different 'biomart host' or try again later.

I have tried to eliminate duplicate IDs and no strategy has worked. The funny thing is that a few months ago, I managed to analyze the same data that I can't analyze now. I´m using the Medicago truncatula (MedtrA17_4.0) annotation (e.g. MTR_0001s0490).

If you would be so kind to guide me on a possible solution.
<img width="1710" alt="Captura de pantalla 2024-03-16 a la(s) 10 44 06" src="https://github.com/Kan-E/RNAseqChef/assets/163657229/3d38de37-6472-4506-a906-3822729a5a19">

Best regards
Ricardo

**Comment by Kan-E** [comment]
Thank you for your inquiry and using RNAseqChef.

It appears to be a bug in the "biomaRt" R package used within RNAseqChef.
(biomaRt is utilized for the analysis of non-model organism in RNAseqChef)
I have reported the bug to the developers of biomaRt, but it is uncertain whether the error will be resolved immediately.
For the time being, regarding enrichment analysis, although it is not a tool I have developed, I recommend using ShinyGO (http://bioinformatics.sdstate.edu/go/) as an alternative.

I apologize for any inconvenience and appreciate your understanding.
