### ISSUE TITLE
Rを用いたインストールができませんでした．

### ISSUE THREAD

**Issue by SodaiKBT** [Kan-E/RNAseqChef#3]
有用なソフトの開発，ありがとうございます．
RNAseqChefを利用したいと思い，Rを用いたLocal installationを試みましたが，エラーとなり使用できませんでした．
R4.3.3を使用しています．下記のようなエラーが生じました．
解決方法がございましたら，ご教授ください．

Listening on http://127.0.0.1:5055
 警告:  Error in $:  'closure' 型のオブジェクトは部分代入可能ではありません

**Comment by Kan-E** [comment]
お問い合わせ有難うございます。
library()で読み込むとアプリが立ち上がらなくなるRpackageが存在します。
このエラーが出た場合には、Rを再起動するか以下のコマンドを実行してください。
```
    lapply(paste("package:",names(sessionInfo()$otherPkgs),sep=""),
           detach,character.only = TRUE,
           unload = TRUE)
```

ただ、PCやRの環境によっては動作しない場合もありますので、localで動かしたい場合にはDockerの使用をお勧めしております。
Dockerを用いたRNAseqChefの起動方法に関しては、近日中に統合TVよりマニュアル動画が公開される予定です。
興味がございましたら、ぜひそちらをご覧ください。
よろしくお願い致します。
