### ISSUE TITLE
Crash after selecting species

### ISSUE THREAD

**Issue by jpm15185** [Kan-E/RNAseqChef#5]
Both local and web-based versions crash when I select Arabidopsis thaliana for my species. This occurs when I am trying to used the Normalized count analysis using tables I constructed with Salmon. 

The program runs fine if I do not select a species, but then I must only use TAIR identifiers instead of common gene names.

**Comment by Kan-E** [comment]
Thank you for your inquiry and for using RNAseqChef. 
I have updated RNAseqChef (v1.1.3) to fix the bug.

**Comment by jpm15185** [comment]
Thank you so much! Your tool is an excellent resource.

From: Kan Etoh ***@***.***>
Date: Monday, November 4, 2024 at 11:57 PM
To: Kan-E/RNAseqChef ***@***.***>
Cc: May, Jared ***@***.***>, Author ***@***.***>
Subject: Re: [Kan-E/RNAseqChef] Crash after selecting species (Issue #5)
WARNING: This message has originated from an External Source. This may be a phishing expedition that can result in unauthorized access to our IT System. Please use proper judgment and caution when opening attachments, clicking links, or responding to this email.

Thank you for your inquiry and for using RNAseqChef.
I have updated RNAseqChef (v1.1.3) to fix the bug.
